# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891\u65f6\u957f'),
        ),
    ]
