# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20221005_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_time',
            field=models.CharField(default=0, max_length=24, verbose_name='\u89c6\u9891\u65f6\u957f'),
        ),
    ]
