# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20221005_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=126, verbose_name='\u8001\u5e08\u5fe0\u544a'),
        ),
    ]
