# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_need_know'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='need_know',
        ),
    ]
