# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-07 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_need_know'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course',
            new_name='lesson',
        ),
    ]
