# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-07 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20221007_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='lesson',
            new_name='course',
        ),
    ]
