# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20221004_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='year',
            field=models.IntegerField(default=66, verbose_name='\u5e74\u9f84'),
        ),
    ]
