# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20221004_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='need_know',
            field=models.CharField(default='', max_length=126, verbose_name='\u8001\u5e08\u5fe0\u544a'),
        ),
    ]
