# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_teacher_need_know'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='is_bannser',
            field=models.BooleanField(default=False, verbose_name='\u53d7\u5426\u8f6e\u64ad'),
        ),
    ]
