# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-12 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_courseorg_is_bannser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='is_bannser',
            new_name='is_banner',
        ),
    ]
