# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2022-10-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221008_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=64, verbose_name='\u5730\u5740'),
        ),
    ]
